djmod/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('myequis/', include('myequis.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

japp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('japp/myequis/', include('myequis.urls')),
    path('japp/admin/', admin.site.urls),
    path('japp/accounts/', include('django.contrib.auth.urls')),
]

myequis/urls.py
from django.urls import path
from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

from . import views

app_name = 'myequis'
urlpatterns = [
    # ex: /myequis/
    path('', views.index, name='index-url'),

    path('export', views.export_data, name='export-url'),

    path('import', views.ImportView.as_view(), name='import-url'),


    # ### BICYCLES ##############################

    # ex: myequis/bicycles/5/
    path('bicycles/<int:bicycle_id>/', views.list_bicycle_detail, name='bicycle-detail-url'),

    # ex: myequis/bicycles/5/records
    path('bicycles/<int:bicycle_id>/records', views.list_records, name='list-records-url'),

    # ex: myequis/bicycles/5/parts
    path('bicycles/<int:bicycle_id>/parts', views.list_bicycle_parts, name='list-bicycle-parts-url'),

    # ex: myequis/bicycles/5/history
    path('bicycles/<int:bicycle_id>/history', views.list_bicycle_history, name='list-bicycle-history-url'),

    # ex: myequis/bicycles/5/history
    path('bicycles/<int:bicycle_id>/timeline', views.list_bicycle_timeline, name='list-bicycle-timeline-url'),

    # ex: myequis/bicycles/5/part/4/mount
    path('bicycles/<int:bicycle_id>/part/<int:part_id>/mount', views.MountMaterialView.as_view(),
         name='mount-material-url'),

    # ex: myequis/bicycles/5/part/4/delete-mounting
    path('bicycles/<int:bicycle_id>/part/<int:part_id>/delete-mounting', views.DeleteMountingView.as_view(),
         name='delete-mounting-url'),

    # ex: myequis/bicycles/5/part/4/exchange
    path('bicycles/<int:bicycle_id>/part/<int:part_id>/exchange', views.ExchangeMaterialView.as_view(),
         name='exchange-material-url'),

    # ex: myequis/bicycles/5/part/4/dismount
    path('bicycles/<int:bicycle_id>/part/<int:part_id>/dismount', views.DismountMaterialView.as_view(),
         name='dismount-material-url'),

    # ### RECORDS ##############################

    # ex: myequis/records/create_record?bicycle_id=1
    path('bicycles/<int:bicycle_id>/create-record', views.CreateRecordView.as_view(), name='create-record-url'),

    # ex: myequis/records/4
    path('records/<int:record_id>/', views.EditRecordView.as_view(), name='edit-record-url'),

    # ### MATERIALS ##############################
    # ex: myequis/materials
    path('materials/active', views.list_active_materials, name='list-active-materials-url'),

    # ex: myequis/materials
    path('materials/stored', views.list_stored_materials, name='list-stored-materials-url'),

    # ex: myequis/materials/disposed
    path('materials/disposed', views.list_disposed_materials, name='list-disposed-materials-url'),

    # ex: myequis/materials/create
    path('materials/create', views.CreateMaterialView.as_view(), name='create-material-url'),

    # ex: myequis/materials/4
    path('materials/<int:material_id>/', views.EditMaterialView.as_view(), name='edit-material-url'),

    # ex: myequis/materials/4/detail
    path('materials/<int:material_id>/detail/', views.list_material_detail, name='material-detail-url'),

    # ### DALs ####################################
    url(
        'manufacture-autocomplete/$',
        views.ManufactureAutocomplete.as_view(),
        name='manufacture-autocomplete',
    ),

    url(
        'material-autocomplete/$',
        views.MaterialAutocomplete.as_view(),
        name='material-autocomplete',
    ),

    url(
        'type-autocomplete/$',
        views.TypeAutocomplete.as_view(create_field='name'),
        name='type-autocomplete',
    ),

]

myequis/models.py
from django.db import models


# A species defines a set of components
class Species(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.name)



# A bicycle is structured into components. For instance front wheel, gear etc.
class Component(models.Model):
    name = models.CharField(max_length=100)
    species = models.ForeignKey(Species, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)


# A bicycle has a species with has components which are maintained
class Bicycle(models.Model):
    name = models.CharField(max_length=100)
    species = models.ForeignKey(Species, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)


# Parts of a component. For instance front wheel: tube, tire, left spokes.
# This is a simplified model of the real world. There is no position within a part, e.g. spokes(1)
class Part(models.Model):
    name = models.CharField(max_length=50)

    component = models.ForeignKey(Component, on_delete=models.CASCADE)

    def __str__(self):
        return "{}/{}/{}".format(self.component.species.name, self.component.name, self.name)


# Point in time of a bycicle to record its data
class Record(models.Model):
    date = models.DateField()
    km = models.DecimalField(max_digits=10, decimal_places=0, )

    bicycle = models.ForeignKey(Bicycle, on_delete=models.CASCADE)

    def __str__(self):
        return "{} {}".format(str(self.date), str(self.bicycle.name))


# Materials can be sorted into a type, e.g. a Chain
class Type(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return str(self.name)

# A material is a physically part of a bicycle. It can be installed at removed, but it must not be used, e.g. when a
# new tube is bought, it has yet no relation to an bicyle.
class Material(models.Model):
    name = models.CharField(max_length=100)

    manufacture = models.CharField(max_length=100)
    size = models.CharField(max_length=100, blank=True, default="")
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    weight = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)

    type = models.ForeignKey(Type, null=True, on_delete=models.CASCADE)

    comment = models.CharField(max_length=50, blank=True, default="")

    stored = models.BooleanField(default=False)

    disposed = models.BooleanField(default=False)
    disposedAt = models.DateField(blank=True, null=True)

    def __str__(self):
        return str(f"{self.id}/{self.manufacture}/{self.name}/{self.disposedAt}")


class Mounting(models.Model):

    material = models.ForeignKey(Material, related_name="material", on_delete=models.CASCADE)

    mount_record = models.ForeignKey(Record, related_name="mount_record", on_delete=models.CASCADE)

    part = models.ForeignKey(Part, on_delete=models.CASCADE)

    comment = models.CharField(max_length=50, blank=True, default="")

    # Optional
    dismount_record = models.ForeignKey(Record, related_name="dismount_record", on_delete=models.CASCADE, blank=True,
                                        null=True)

    @property
    def active(self):
        return self.dismount_record is None


    def __str__(self):
        return "{}/{}/{} {} active={}".format(str(self.mount_record.bicycle.name),
                                              str(self.part.name),
                                              str(self.material.name),
                                              str(self.mount_record.date),
                                              str(self.active),
                                              str(self.comment),
                                              )

myequis/views.py
import logging
import io
import zipfile

from dal import autocomplete
from datetime import datetime
from django.db import DatabaseError, transaction
from django.db.models import Q, OuterRef, Exists, Subquery
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.datastructures import MultiValueDictKeyError
from django.views.generic.edit import UpdateView, CreateView
from os import path
from myequis.models import Bicycle, Component, Material, Mounting, Part, Record, Species, Type
from tablib import Dataset, UnsupportedFormat
from .forms import get_material_names, get_manufacture_names,\
    CreateRecordForm, CreateMaterialForm, DeleteMountingForm, MountForm,\
    DismountForm, ExchangeMountingForm, EditRecordForm, EditMaterialForm,\
    ImportForm

from .resources import BicycleResource, ComponentResource, MaterialResource,\
    MountingResource, PartResource, RecordResource, SpeciesResource,\
    TypeResource

# Get an instance of a logger
logger = logging.getLogger(__name__)

# Keys for request.session items
KEY_MESSAGE = 'JAPP_SESSION_MESSAGE'

KEY_FROM = 'JAPP_SESSION_FROM'

# For Mounting tabs
KEY_MOUNTING_TABS = 'JAPP_SESSION_MOUNTING_TABS'

# Use this as GET parameter when leaving an dialog, so the calling views
# can prevent from wrong backwards navigation
VAR_BACK_NAVIGATION = 'back_navigation'

def zip_files(files, suffix):
    outfile = io.BytesIO()
    with zipfile.ZipFile(outfile, 'w') as zf:
        for n in files:
            zf.writestr("{}.{}".format(n["name"], suffix), n["data"])
    return outfile.getvalue()


def unzip_files(zip_file):
    """
    returs dictionary for every data type
    """

    ret = dict()

    with zipfile.ZipFile(zip_file, 'r') as z:
        logger.warning(f"ZipFile list:{z.namelist()}")

        for n in z.namelist():
            dataset = Dataset()
            (name, suffix) = path.splitext(n)
            suffix = suffix[1:]
            logger.warning(
                f"unzip_files name and suffix = {name} and {suffix}")
            with z.open(n) as myfile:
                ret[name] = dataset.load(
                    myfile.read().decode('utf-8'), format=suffix)

    # logger.warning(f"unzip_files ret = {ret}")

    return ret


class TypeAutocomplete(autocomplete.Select2QuerySetView):

    def get_queryset(self):

        # Don't forget to filter out results depending on the visitor !
        if not self.request.user.is_authenticated:
            return Type.objects.none()

        qs = Type.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs


class ManufactureAutocomplete(autocomplete.Select2ListView):
    """
        Returns list with manufacture names as tuples, unique and ordered alphabetically.
        The query value will be added to the top of the list, if new.
        Why tuples? This only works proper with new values and q mixing
    """
    def get_list(self):
        list = get_manufacture_names()

        if self.q:
            # logger.warning(f"MaterialAutocomplete q=: {self.q}")
            list.insert(0, (self.q, self.q))

        # logger.warning(f"MaterialAutocomplete: {list}")

        return list


class MaterialAutocomplete(autocomplete.Select2ListView):
    """
        Returns list with material names as tuples, unique and ordered alphabetically.
        The query value will be added to the top of the list, if new.
        Why tuples? This only works proper with new values and q mixing
    """
    def get_list(self):
        list = get_material_names()

        if self.q:
            # logger.warning(f"MaterialAutocomplete q=: {self.q}")
            list.insert(0, (self.q, self.q))

        # logger.warning(f"MaterialAutocomplete: {list}")

        return list


class ImportView(LoginRequiredMixin, CreateView):

    def get(self, request, *args, **kwargs):

        # Where did I come from
        request.session[type(self).__name__] = request.META.get('HTTP_REFERER', '/')

        # Init message
        request.session[KEY_MESSAGE] = None

        # If called with data, clean() will be processed!
        form = ImportForm({})

        template = loader.get_template('myequis/import.html')
        return HttpResponse(template.render({
            'form': form,
            # 'import_disabled': "true", No good idea - give the user a chance to decide by himself
        }, request))

    def post(self, request, *args, **kwargs):
        logger.warning("ImportView POST request.POST: {} request.FILES:{}".format(
            str(request.POST), str(request.FILES)))

        if 'cancel' in request.POST:
            request.session[KEY_MESSAGE] = "Import canceled"
            return HttpResponseRedirect(request.session[type(self).__name__])

        form = ImportForm(request.POST, request.FILES)
        # logger.warning("form: " + str(form))
        # logger.warning("form cleaned_data: " + str(form.cleaned_data))

        output = []

        if 'import' in request.POST:
            logger.warning("import")

        # logger.warning(f"importData={request.FILES['importData'].name}")

        if form.is_valid():
            logger.warning("is valid. form.cleaned_data={}".format(
                str(form.cleaned_data)))

            form.check_data()

            logger.warning(f"request={request.FILES['importData']}")
            data_count = 0
            error = False

            try:
                datasets = unzip_files(request.FILES['importData'])
                logger.warning(f"datasets={datasets}")

            except (UnsupportedFormat, MultiValueDictKeyError) as e:
                logger.error(e)
                message = str(e)
                error = True

            if error is False:

                try:
                    with transaction.atomic():
                        output.append(
                            f"Loaded file: {request.FILES['importData']}")

                        Mounting.objects.all().delete()
                        Material.objects.all().delete()
                        Record.objects.all().delete()
                        Bicycle.objects.all().delete()
                        Part.objects.all().delete()
                        Component.objects.all().delete()
                        Species.objects.all().delete()

                        species_resource = SpeciesResource()
                        species_data = datasets["Species"]
                        data_count = data_count + len(species_data)
                        logger.warning(f"species_data={species_data}")
                        output.append(
                            f"Species: {len(Species.objects.all())} <-- {len(species_data)}")
                        result_species = species_resource.import_data(
                            species_data)
                        if result_species.has_errors():
                            message = "Invalid Species data"
                        error = error or result_species.has_errors()

                        component_resource = ComponentResource()
                        component_data = datasets["Component"]
                        data_count = data_count + len(component_data)
                        logger.warning(f"component_data={component_data}")
                        output.append(
                            f"Component: {len(Component.objects.all())} <-- {len(component_data)}")
                        result_component = component_resource.import_data(
                            component_data)
                        if result_component.has_errors():
                            message = "Invalid Components data"
                        error = error or result_component.has_errors()

                        part_resource = PartResource()
                        part_data = datasets["Part"]
                        data_count = data_count + len(part_data)
                        logger.warning(f"part_data={part_data}")
                        output.append(
                            f"Part: {len(Part.objects.all())} <-- {len(part_data)}")
                        result_part = part_resource.import_data(part_data)
                        if result_part.has_errors():
                            message = "Invalid Parts data"
                        error = error or result_part.has_errors()

                        bicycle_resource = BicycleResource()
                        bicycle_data = datasets["Bicycle"]
                        data_count = data_count + len(bicycle_data)
                        logger.warning(f"bicycle_data={bicycle_data}")
                        output.append(
                            f"Bicycle: {len(Bicycle.objects.all())} <-- {len(bicycle_data)}")
                        result_bicycle = bicycle_resource.import_data(
                            bicycle_data)
                        if result_bicycle.has_errors():
                            message = "Invalid Bicycles data"
                        error = error or result_bicycle.has_errors()

                        record_resource = RecordResource()
                        record_data = datasets["Record"]
                        data_count = data_count + len(record_data)
                        logger.warning(f"record_data={record_data}")
                        output.append(
                            f"Record: {len(Record.objects.all())} <-- {len(record_data)}")
                        result_record = record_resource.import_data(
                            record_data)
                        if result_record.has_errors():
                            message = "Invalid Records data"
                        error = error or result_record.has_errors()

                        type_resource = TypeResource()

myequis/templates/myequis/bicycle_parts.html
{% extends "base.html" %}

{% block nav-items %}
{% endblock %}


{% block main %}

{% with var=bicycle.name|add:" Parts"  %}
{% include "page-title.html" with title=var  %}
{% endwith %}

{% include "nav-open.html" %}

{% url 'myequis:bicycle-detail-url' bicycle.id as nav_url %}
{% include "nav-item.html" with url=nav_url title="Back" %}
{% include "nav-close.html" %}

<div>
  {% if data_list %}
  {% for data in data_list %}

  {% url 'myequis:bicycle-detail-url' bicycle.id as back_url %}
  {% if not data.prev %}
  {% firstof "disabled" as prev_status  %}
  {% else %}
  {% firstof "" as prev_status  %}
  {% endif %}

  {% if not data.next %}
  {% firstof "disabled" as next_status  %}
  {% else %}
  {% firstof "" as next_status  %}
  {% endif %}

  {% include "nav-line.html" with title=data.name back_url=data.back prev_url=data.prev prev_status=prev_status next_url=data.next next_status=next_status %}


  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Part</th>
          <th scope="col">Material</th>
          <th scope="col">Mounted at</th>
          <th scope="col">KM</th>
        </tr>
      </thead>
      {% for part in data.parts %}
      <tr>

        {% if part.material %}
        <td onclick="tdClick('{% url 'myequis:exchange-material-url' bicycle.id part.part.id %}');">
          {{ part.part.name }}
        </td>
        {% else %}
        <td onclick="tdClick('{% url 'myequis:mount-material-url' bicycle.id part.part.id %}');">
          {{ part.part.name }}
        </td>
        {% endif %}

        {% if part.material %}
        <td onclick="tdClick('{% url 'myequis:material-detail-url' part.material.id %}');">
          <span class="">
          {{ part.material.type }} &#903;
          </span>
          <span class="text-uppercase">
          {{ part.material.manufacture }} &#903;
          </span>
          <span class="">
          {{ part.material.name }}
          </span>
          <div class="text-muted">
            <div>
              {{ part.material.comment }}
            </div>
            <div>
              {{ part.mounting.comment }}
            </div>
          </div>
        </td>
        {% else %}
        <td>{{ part.material.name }}</td>
        {% endif %}

        <td>{{ part.mounting.mount_record.date }}</td>
        <td>{{ part.distance }}</td>
      </tr>
      {% endfor %}
    </table>
    {% endfor%}
    {% else %}
    <p>No components yet</p>
    {% endif %}
  </div>
</div>

{% endblock %}

myequis/templates/myequis/bicycle_timeline.html
`{% extends "base.html" %}
{% load static %}

{% block nav-items %}
{% endblock %}


{% block main %}


{% with var=bicycle.name|add:" Timeline"  %}
{% include "page-title.html" with title=var  %}
{% endwith %}

{% include "nav-open.html" %}
{% url 'myequis:bicycle-detail-url' bicycle.id as nav_url %}
{% include "nav-item.html" with url=nav_url title='Back' %}
{% include "nav-close.html" %}

{% if year_data_list %}
{% for y in year_data_list %}

{% url 'myequis:bicycle-detail-url' bicycle.id as back_url %}
{% if y.prev == "None" %}
{% firstof "disabled" as prev_status  %}
{% else %}
{% firstof "" as prev_status  %}
{% endif %}

{% if y.next == "None" %}
{% firstof "disabled" as next_status  %}
{% else %}
{% firstof "" as next_status  %}
{% endif %}

{% include "nav-line.html" with title=y.year back_url=y.back prev_url=y.prev prev_status=prev_status next_url=y.next next_status=next_status %}


{% for d in y.data_list %}

<div class="d-flex justify-content-between  pt-4 pl-2 pr-2 border-bottom border-primary">
  <div>
    <H3>
      {{ d.record.date }}
    </H3>
  </div>
  <div>
    {{ d.record.km }} km
  </div>

</div>
{% for p in d.part_list %}
<div class="pt-4">
  <H3>
    {{ p.part.component.name }} / {{ p.part.name }}
  </H3>
</div>

<div class="d-flex flex-wrap" >
  {% for m in p.mounting_list %}


  <div class="card m-1" style="width: 30rem;">
    <div class="card-body">
      <div class="container">
        <div class="row justify-content-start">
          <div class="col-3 justify-content-start">
            {% if m.mount_record.date == d.record.date%}
            {% if m.dismount_record.date == d.record.date%}
            <img src= "{% static '/myequis/arrow-left-right.svg' %}" width="40" height="40" alt="EXCHANGE ">
            {% else %}
            <img src= "{% static '/myequis/file-earmark-plus.svg' %}" width="40" height="40" alt="IN">
            {% endif %}
            {% else %}
            <img src= "{% static '/myequis/file-earmark-minus-fill.svg' %}" width="40" height="40" alt="OUT">
            {% endif %}
          </div>
          <div class="col-9" onclick="tdClick('{% url 'myequis:material-detail-url' m.material.id %}');">
            <div class="text-secondary">
              {{ m.material.type }}
            </div>
            <div class="text-uppercase">
              {{ m.material.manufacture }}
            </div>
            <h5>
              <div class="font-weight-bold">
                <span>
                  {{ m.material.name }}
                </span>
              </div>
            </h5>
          </div>
        </div>

        {% if m.material.size %}
        <div class="row justify-content-start">
          <div class="col-3 text-right">
            Size
          </div>
          <div class="col-9">
            {{ m.material.size }}
          </div>
        </div>
        {% endif %}


        {% if m.material.weight %}
        <div class="row justify-content-start">
          <div class="col-3 text-right">
            Weight
          </div>
          <div class="col-9">
            {{ m.material.weight }}
          </div>
        </div>
        {% endif %}

        {% if m.material.price %}
        <div class="row justify-content-start">
          <div class="col-3 text-right">
            Price
          </div>
          <div class="col-9">
            {{ m.material.price }}
          </div>
        </div>
        {% endif %}

        {% if m.material.stored %}
        <div class="row justify-content-start">
          <div class="col-3 text-right">
            Stored
          </div>
          <div class="col-9">
            &#x1F5F9;
          </div>
        </div>
        {% endif %}


        {% if m.material.disposed %}
        <div class="row justify-content-start">
          <div class="col-3 text-right">
            Disposed at
          </div>
          <div class="col-9">
            {{ m.material.disposedAt }}
          </div>
        </div>
        {% endif %}

        <div class="row justify-content-start">
        </div>


      </div>

      <div>
        <div class="text-muted">
          <div>
            {{ m.material.comment }}
          </div>
          <div>
            {{ m.comment }}
          </div>
        </div>
      </div>

    </div>
  </div>
  {% endfor%}
</div>
{% endfor%}
{% endfor%}
{% endfor%}

{% else %}

{% include "nav-open.html" %}
{% url 'myequis:bicycle-detail-url' bicycle.id as back_url %}
{% include "nav-item.html" with url=back_url title="Back" %}
{% include "nav-close.html" %}

<p>Nothing recorded yet</p>

{% endif %}


{% endblock %}
`

myequis/templates/myequis/create_record.html
{% extends "form-base.html" %}

{% block nav-items %}
{% endblock %}

{% block header %}
{{ record.bicycle.name }}
{% endblock %}

{% block main %}
{% include "article-title.html" with title="New Record" %}

<form  action="" method="post" >
  {% csrf_token %}

  <div>{{ form.date.label }}</div>
  <div >{{ form.date }}</div >

    <div >{{ form.km.label }}</div>
    <div >{{ form.km }}</div>

    {{ form.bicycle_id }}

    {% include "form-buttons-open.html" %}
    <input  {% include "form-button-class.html" %} type="submit" value="Create">
    <input  {% include "form-button-class.html" %} type="submit" name="cancel" value="Cancel">
    {% include "form-buttons-close.html" %}
  </form>

  {% endblock %}

myequis/templates/myequis/delete_mounting.html
{% extends "form-base.html" %}

{% block main %}

{% with bicycle.name|add:" | "|add:part.name|add:" |  Edit Mounting " as title %}
{% include "article-title.html" with title=title %}
{% endwith %}

<ul class="nav nav-tabs nav-fill">
  <li class="nav-item">
    <a class="nav-link active disabled" href="#">Delete</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'myequis:exchange-material-url' bicycle.id part.id %}?tabchange=true"">Exchange</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'myequis:dismount-material-url' bicycle.id part.id %}?tabchange=true"">Dismount</a>
  </li>
</ul>

{% if mounting.comment %}
<div>Comment: {{ mounting.comment }}</div>
{% endif %}

<form action="" method="post">
  {% csrf_token %}

  {% include "section-title.html" with title="Materials" %}

  <div class="table-responsive">
    <table id="material-table" class="table">
      <thead>
        <tr>
          <th>Material</th>
          <th>Size</th>
          <th>Price</th>
        </tr>
      </thead>
      <tr>
        <td >
          <span class="">
          {{ mounting.material.type }} &#903;
          </span>
          <span class="text-uppercase">
          {{ mounting.material.manufacture }} &#903;
          </span>
          <span class="">
          {{ mounting.material.name }}
          </span>
          <div class="text-muted">
            {{ mounting.material.comment }}
          </div>
        </td>

        <td>{{ mounting.material.size }}</td>
        <td>{{ mounting.material.price }}</td>
      </tr>
    </table>
  </div>

  {% include "section-title.html" with title="Record" %}

  <div class="table-responsive">
    <table id="record-table" class="table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Value<br>[km]</th>
        </tr>
      </thead>
      <tr>
        <td>{{ mounting.mount_record.date }}</td>
        <td>{{ mounting.mount_record.km }}</td>
      </tr>
    </table>
  </div>

  {{ form.bicycle_id }}
  {{ form.mounting_id }}

  {% include "form-buttons-open.html" %}
  <input  {% include "form-button-class.html" %} type="submit" name="delete" value="Delete" onclick="return confirm('Delete dataset?')">
  <input  {% include "form-button-class.html" %} type="submit" name="cancel" value="Cancel">
  {% include "form-buttons-close.html" %}
</form>
{% endblock %}

myequis/templates/myequis/index.html
  {% extends "base.html" %}

{% block main %}

{% include "article-title.html" with title="Bicycles" %}

{% if bicycles %}
<table class="table table-hover">
  <thead>

    <tr>
      <th scope="col">Name</th>
    </tr>
  </thead>
  <tbody>
    {% for bicycle in bicycles %}
    <tr>
      <td>
        <a class="nav-link"  href="{% url 'myequis:bicycle-detail-url' bicycle.id %}">{{ bicycle.name }}</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% else %}

<p>No bicycles yet</p>

{% endif %}

{% include "article-title.html" with title="Materials" %}

{% include "nav-open.html" %}

{% url 'myequis:list-disposed-materials-url' as nav_url %}
{% include "nav-item.html" with url=nav_url title="Disposed" %}

{% url 'myequis:list-stored-materials-url' as nav_url %}
{% include "nav-item.html" with url=nav_url title="Stored" %}

{% url 'myequis:list-active-materials-url' as nav_url %}
{% include "nav-item.html" with url=nav_url title="Active" %}

{% include "nav-close.html" %}

{% if materials %}

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Material</th>
        <th scope="col" class="d-none d-md-block">Price</th>
      </tr>
    </thead>
    {% for material in materials %}
    <tr>
      <td>
        <span class="">
        {{ material.type }} &#903;
        </span>
        <span class="text-uppercase">
        {{ material.manufacture }} &#903;
        </span>
        <span class="">
        {{ material.name }}
        </span>

        <div class="text-muted">
          {{ material.comment }}
        </div>
      </td>
      <td class="d-none d-md-block">{{ material.price }}</td>
    </tr>
    {% endfor %}
  </table>
</div>
{% else %}

<p>No unused materials</p>

{% endif %}

{% include "article-title.html" with title="Bulk Operations"%}

{% include "nav-open.html" %}

{% url 'admin:index' as nav_url %}
{% include "nav-item.html" with url=nav_url title="Admin" %}

{% url 'myequis:export-url' as nav_url %}
{% include "nav-item.html" with url=nav_url title="Export" %}

{% url 'myequis:import-url' as nav_url %}
{% include "nav-item.html" with url=nav_url title="Import" %}

{% include "nav-close.html" %}

{% endblock %}