djmod/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('myequis/', include('myequis.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

japp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('japp/myequis/', include('myequis.urls')),
    path('japp/admin/', admin.site.urls),
    path('japp/accounts/', include('django.contrib.auth.urls')),
]

myequis/urls.py
from django.urls import path
from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

from . import views

app_name = 'myequis'
urlpatterns = [
    # ex: /myequis/
    path('', views.index, name='index-url'),

    path('export', views.export_data, name='export-url'),

    path('import', views.ImportView.as_view(), name='import-url'),


    # ### BICYCLES ##############################

    # ex: myequis/bicycles/5/
    path('bicycles/<int:bicycle_id>/', views.list_bicycle_detail, name='bicycle-detail-url'),

    # ex: myequis/bicycles/5/records
    path('bicycles/<int:bicycle_id>/records', views.list_records, name='list-records-url'),

    # ex: myequis/bicycles/5/parts
    path('bicycles/<int:bicycle_id>/parts', views.list_bicycle_parts, name='list-bicycle-parts-url'),

    # ex: myequis/bicycles/5/history
    path('bicycles/<int:bicycle_id>/history', views.list_bicycle_history, name='list-bicycle-history-url'),

    # ex: myequis/bicycles/5/history
    path('bicycles/<int:bicycle_id>/timeline', views.list_bicycle_timeline, name='list-bicycle-timeline-url'),

    # ex: myequis/bicycles/5/part/4/mount
    path('bicycles/<int:bicycle_id>/part/<int:part_id>/mount', views.MountMaterialView.as_view(),
         name='mount-material-url'),

    # ex: myequis/bicycles/5/part/4/delete-mounting
    path('bicycles/<int:bicycle_id>/part/<int:part_id>/delete-mounting', views.DeleteMountingView.as_view(),
         name='delete-mounting-url'),

    # ex: myequis/bicycles/5/part/4/exchange
    path('bicycles/<int:bicycle_id>/part/<int:part_id>/exchange', views.ExchangeMaterialView.as_view(),
         name='exchange-material-url'),

    # ex: myequis/bicycles/5/part/4/dismount
    path('bicycles/<int:bicycle_id>/part/<int:part_id>/dismount', views.DismountMaterialView.as_view(),
         name='dismount-material-url'),

    # ### RECORDS ##############################

    # ex: myequis/records/create_record?bicycle_id=1
    path('bicycles/<int:bicycle_id>/create-record', views.CreateRecordView.as_view(), name='create-record-url'),

    # ex: myequis/records/4
    path('records/<int:record_id>/', views.EditRecordView.as_view(), name='edit-record-url'),

    # ### MATERIALS ##############################
    # ex: myequis/materials
    path('materials/active', views.list_active_materials, name='list-active-materials-url'),

    # ex: myequis/materials
    path('materials/stored', views.list_stored_materials, name='list-stored-materials-url'),

    # ex: myequis/materials/disposed
    path('materials/disposed', views.list_disposed_materials, name='list-disposed-materials-url'),

    # ex: myequis/materials/create
    path('materials/create', views.CreateMaterialView.as_view(), name='create-material-url'),

    # ex: myequis/materials/4
    path('materials/<int:material_id>/', views.EditMaterialView.as_view(), name='edit-material-url'),

    # ex: myequis/materials/4/detail
    path('materials/<int:material_id>/detail/', views.list_material_detail, name='material-detail-url'),

    # ### DALs ####################################
    url(
        'manufacture-autocomplete/$',
        views.ManufactureAutocomplete.as_view(),
        name='manufacture-autocomplete',
    ),

    url(
        'material-autocomplete/$',
        views.MaterialAutocomplete.as_view(),
        name='material-autocomplete',
    ),

    url(
        'type-autocomplete/$',
        views.TypeAutocomplete.as_view(create_field='name'),
        name='type-autocomplete',
    ),

]

myequis/models.py
from django.db import models


# A species defines a set of components
class Species(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.name)



# A bicycle is structured into components. For instance front wheel, gear etc.
class Component(models.Model):
    name = models.CharField(max_length=100)
    species = models.ForeignKey(Species, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)


# A bicycle has a species with has components which are maintained
class Bicycle(models.Model):
    name = models.CharField(max_length=100)
    species = models.ForeignKey(Species, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)


# Parts of a component. For instance front wheel: tube, tire, left spokes.
# This is a simplified model of the real world. There is no position within a part, e.g. spokes(1)
class Part(models.Model):
    name = models.CharField(max_length=50)

    component = models.ForeignKey(Component, on_delete=models.CASCADE)

    def __str__(self):
        return "{}/{}/{}".format(self.component.species.name, self.component.name, self.name)


# Point in time of a bycicle to record its data
class Record(models.Model):
    date = models.DateField()
    km = models.DecimalField(max_digits=10, decimal_places=0, )

    bicycle = models.ForeignKey(Bicycle, on_delete=models.CASCADE)

    def __str__(self):
        return "{} {}".format(str(self.date), str(self.bicycle.name))


# Materials can be sorted into a type, e.g. a Chain
class Type(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return str(self.name)

# A material is a physically part of a bicycle. It can be installed at removed, but it must not be used, e.g. when a
# new tube is bought, it has yet no relation to an bicyle.
class Material(models.Model):
    name = models.CharField(max_length=100)

    manufacture = models.CharField(max_length=100)
    size = models.CharField(max_length=100, blank=True, default="")
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    weight = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True)

    type = models.ForeignKey(Type, null=True, on_delete=models.CASCADE)

    comment = models.CharField(max_length=50, blank=True, default="")

    stored = models.BooleanField(default=False)

    disposed = models.BooleanField(default=False)
    disposedAt = models.DateField(blank=True, null=True)

    def __str__(self):
        return str(f"{self.id}/{self.manufacture}/{self.name}/{self.disposedAt}")


class Mounting(models.Model):

    material = models.ForeignKey(Material, related_name="material", on_delete=models.CASCADE)

    mount_record = models.ForeignKey(Record, related_name="mount_record", on_delete=models.CASCADE)

    part = models.ForeignKey(Part, on_delete=models.CASCADE)

    comment = models.CharField(max_length=50, blank=True, default="")

    # Optional
    dismount_record = models.ForeignKey(Record, related_name="dismount_record", on_delete=models.CASCADE, blank=True,
                                        null=True)

    @property
    def active(self):
        return self.dismount_record is None


    def __str__(self):
        return "{}/{}/{} {} active={}".format(str(self.mount_record.bicycle.name),
                                              str(self.part.name),
                                              str(self.material.name),
                                              str(self.mount_record.date),
                                              str(self.active),
                                              str(self.comment),
                                              )

myequis/views.py
import logging
import io
import zipfile

from dal import autocomplete
from datetime import datetime
from django.db import DatabaseError, transaction
from django.db.models import Q, OuterRef, Exists, Subquery
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.datastructures import MultiValueDictKeyError
from django.views.generic.edit import UpdateView, CreateView
from os import path
from myequis.models import Bicycle, Component, Material, Mounting, Part, Record, Species, Type
from tablib import Dataset, UnsupportedFormat
from .forms import get_material_names, get_manufacture_names,\
    CreateRecordForm, CreateMaterialForm, DeleteMountingForm, MountForm,\
    DismountForm, ExchangeMountingForm, EditRecordForm, EditMaterialForm,\
    ImportForm

from .resources import BicycleResource, ComponentResource, MaterialResource,\
    MountingResource, PartResource, RecordResource, SpeciesResource,\
    TypeResource

# Get an instance of a logger
logger = logging.getLogger(__name__)

# Keys for request.session items
KEY_MESSAGE = 'JAPP_SESSION_MESSAGE'

KEY_FROM = 'JAPP_SESSION_FROM'

# For Mounting tabs
KEY_MOUNTING_TABS = 'JAPP_SESSION_MOUNTING_TABS'

# Use this as GET parameter when leaving an dialog, so the calling views
# can prevent from wrong backwards navigation
VAR_BACK_NAVIGATION = 'back_navigation'

def zip_files(files, suffix):
    outfile = io.BytesIO()
    with zipfile.ZipFile(outfile, 'w') as zf:
        for n in files:
            zf.writestr("{}.{}".format(n["name"], suffix), n["data"])
    return outfile.getvalue()


def unzip_files(zip_file):
    """
    returs dictionary for every data type
    """

    ret = dict()

    with zipfile.ZipFile(zip_file, 'r') as z:
        logger.warning(f"ZipFile list:{z.namelist()}")

        for n in z.namelist():
            dataset = Dataset()
            (name, suffix) = path.splitext(n)
            suffix = suffix[1:]
            logger.warning(
                f"unzip_files name and suffix = {name} and {suffix}")
            with z.open(n) as myfile:
                ret[name] = dataset.load(
                    myfile.read().decode('utf-8'), format=suffix)

    # logger.warning(f"unzip_files ret = {ret}")

    return ret


class TypeAutocomplete(autocomplete.Select2QuerySetView):

    def get_queryset(self):

        # Don't forget to filter out results depending on the visitor !
        if not self.request.user.is_authenticated:
            return Type.objects.none()

        qs = Type.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs


class ManufactureAutocomplete(autocomplete.Select2ListView):
    """
        Returns list with manufacture names as tuples, unique and ordered alphabetically.
        The query value will be added to the top of the list, if new.
        Why tuples? This only works proper with new values and q mixing
    """
    def get_list(self):
        list = get_manufacture_names()

        if self.q:
            # logger.warning(f"MaterialAutocomplete q=: {self.q}")
            list.insert(0, (self.q, self.q))

        # logger.warning(f"MaterialAutocomplete: {list}")

        return list


class MaterialAutocomplete(autocomplete.Select2ListView):
    """
        Returns list with material names as tuples, unique and ordered alphabetically.
        The query value will be added to the top of the list, if new.
        Why tuples? This only works proper with new values and q mixing
    """
    def get_list(self):
        list = get_material_names()

        if self.q:
            # logger.warning(f"MaterialAutocomplete q=: {self.q}")
            list.insert(0, (self.q, self.q))

        # logger.warning(f"MaterialAutocomplete: {list}")

        return list


class ImportView(LoginRequiredMixin, CreateView):

    def get(self, request, *args, **kwargs):

        # Where did I come from
        request.session[type(self).__name__] = request.META.get('HTTP_REFERER', '/')

        # Init message
        request.session[KEY_MESSAGE] = None

        # If called with data, clean() will be processed!
        form = ImportForm({})

        template = loader.get_template('myequis/import.html')
        return HttpResponse(template.render({
            'form': form,
            # 'import_disabled': "true", No good idea - give the user a chance to decide by himself
        }, request))

    def post(self, request, *args, **kwargs):
        logger.warning("ImportView POST request.POST: {} request.FILES:{}".format(
            str(request.POST), str(request.FILES)))

        if 'cancel' in request.POST:
            request.session[KEY_MESSAGE] = "Import canceled"
            return HttpResponseRedirect(request.session[type(self).__name__])

        form = ImportForm(request.POST, request.FILES)
        # logger.warning("form: " + str(form))
        # logger.warning("form cleaned_data: " + str(form.cleaned_data))

        output = []

        if 'import' in request.POST:
            logger.warning("import")

        # logger.warning(f"importData={request.FILES['importData'].name}")

        if form.is_valid():
            logger.warning("is valid. form.cleaned_data={}".format(
                str(form.cleaned_data)))

            form.check_data()

            logger.warning(f"request={request.FILES['importData']}")
            data_count = 0
            error = False

            try:
                datasets = unzip_files(request.FILES['importData'])
                logger.warning(f"datasets={datasets}")

            except (UnsupportedFormat, MultiValueDictKeyError) as e:
                logger.error(e)
                message = str(e)
                error = True

            if error is False:

                try:
                    with transaction.atomic():
                        output.append(
                            f"Loaded file: {request.FILES['importData']}")

                        Mounting.objects.all().delete()
                        Material.objects.all().delete()
                        Record.objects.all().delete()
                        Bicycle.objects.all().delete()
                        Part.objects.all().delete()
                        Component.objects.all().delete()
                        Species.objects.all().delete()

                        species_resource = SpeciesResource()
                        species_data = datasets["Species"]
                        data_count = data_count + len(species_data)
                        logger.warning(f"species_data={species_data}")
                        output.append(
                            f"Species: {len(Species.objects.all())} <-- {len(species_data)}")
                        result_species = species_resource.import_data(
                            species_data)
                        if result_species.has_errors():
                            message = "Invalid Species data"
                        error = error or result_species.has_errors()

                        component_resource = ComponentResource()
                        component_data = datasets["Component"]
                        data_count = data_count + len(component_data)
                        logger.warning(f"component_data={component_data}")
                        output.append(
                            f"Component: {len(Component.objects.all())} <-- {len(component_data)}")
                        result_component = component_resource.import_data(
                            component_data)
                        if result_component.has_errors():
                            message = "Invalid Components data"
                        error = error or result_component.has_errors()

                        part_resource = PartResource()
                        part_data = datasets["Part"]
                        data_count = data_count + len(part_data)
                        logger.warning(f"part_data={part_data}")
                        output.append(
                            f"Part: {len(Part.objects.all())} <-- {len(part_data)}")
                        result_part = part_resource.import_data(part_data)
                        if result_part.has_errors():
                            message = "Invalid Parts data"
                        error = error or result_part.has_errors()

                        bicycle_resource = BicycleResource()
                        bicycle_data = datasets["Bicycle"]
                        data_count = data_count + len(bicycle_data)
                        logger.warning(f"bicycle_data={bicycle_data}")
                        output.append(
                            f"Bicycle: {len(Bicycle.objects.all())} <-- {len(bicycle_data)}")
                        result_bicycle = bicycle_resource.import_data(
                            bicycle_data)
                        if result_bicycle.has_errors():
                            message = "Invalid Bicycles data"
                        error = error or result_bicycle.has_errors()

                        record_resource = RecordResource()
                        record_data = datasets["Record"]
                        data_count = data_count + len(record_data)
                        logger.warning(f"record_data={record_data}")
                        output.append(
                            f"Record: {len(Record.objects.all())} <-- {len(record_data)}")
                        result_record = record_resource.import_data(
                            record_data)
                        if result_record.has_errors():
                            message = "Invalid Records data"
                        error = error or result_record.has_errors()

                        type_resource = TypeResource()

myequis/templates/article-title.html
{% if id %}
<h2 id='{{id}}' class="bg-primary text-white pl-3 pt-2 pb-2" >
  {{ title }}
</h2>
{% else %}
<h2 class="bg-primary text-white pl-3 pt-2 pb-2" >
  {{ title }}
</h2>
{% endif %}

myequis/templates/base.html
<!DOCTYPE html>
<html lang="en" style="max-width: 80rem; text-align: center; margin-left:auto; margin-right:auto;">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load static %}
    {% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
    {% bootstrap_css %}         {# Embed Bootstrap CSS #}
    {% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
    {{ form.media }}            {# Adds date-picker required JS and CSS #}

    <link rel="icon"href="{% static '/myequis/favicon.ico' %}">

    <script language="JavaScript">
        function tdClick(url){
            window.open(url, "_self");
        }
    </script>


    <title>
      {% block title %}My Equis{% endblock %}
    </title>

  </head>

  <body class="bg-light">

    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-secondary border-bottom ">
          <a class="navbar-brand" href="{% url 'myequis:index-url' %}">
            <img src= "{% static '/myequis/logo.png' %}" width="30" height="30" alt="Logo">
            My Equis
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-3 mr-auto">
              {% if user.is_authenticated %}
                <li class="nav-item">
                  <span class="navbar-text"> Hi {{ user.username }}! </span>
                </li>
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'logout' %}">Log Out</a>
                </li>
              {% else %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
              {% endif %}              {% block nav-items %}{% endblock %}
            </ul>
          </div>
        </nav>

      {% if message %}
          <div class="alert alert-danger m-0" role="alert">
              <strong>{{ message|escape }}</strong>
          </div>
      {% endif %}

    </<header>

    <div id="main">
      <main class="main">
        {% block main %}{% endblock %}
      </main>
    </div>

  </body>
  <footer class="pt-3 pb-1 text-muted text-center text-small bg-secondary">
    <p class="text-white">© 2021 Christian Schuzlendorff</p>
  </footer>

</html>

myequis/templates/form-base.html
<!DOCTYPE html>
<html lang="en" style="max-width: 80rem; text-align: center; margin-left:auto; margin-right:auto;">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  {% load static %}
  {% load bootstrap4 %}       {# import bootstrap4/bootstrap3 #}
  {% bootstrap_css %}         {# Embed Bootstrap CSS #}
  {% bootstrap_javascript jquery='full' %}  {# Embed Bootstrap JS+jQuery #}
  {{ form.media }}            {# Adds date-picker required JS and CSS #}

  <link rel="icon"href="{% static '/myequis/favicon.ico' %}">

  {% block script %}
  <script language="JavaScript">
  function tdClick(url){
    window.open(url, "_self");
  }
  </script>

  {% endblock %}

  <title>
    {% block title %}My Equis{% endblock %}
  </title>

</head>

<body class="bg-light">

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-secondary border-bottom ">
      <a class="navbar-brand" href="{% url 'myequis:index-url' %}">My Equis</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-3 mr-auto">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text"> Hi {{ user.username }}! </span>
          </li>
          <li class="nav-item active">
            <a class="nav-link active" href="{% url 'logout' %}">Log Out</a>
          </li>
          {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          {% endif %}              {% block nav-items %}{% endblock %}
        </ul>
      </div>
    </nav>

    </<header>

      <div id="main">
        <main class="main bg-secondary">

          <div class="p-2" style="max-width: 80rem;">
            <div class="p-2 bg-light">

              {% if form.errors %}
              {% for field in form %}
              {% for error in field.errors %}
              <div class="alert alert-danger" role="alert">
                {{ error|escape }}
              </div>
              {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
              <div class="alert alert-danger" role="alert">
                <strong>{{ error|escape }}</strong>
              </div>
              {% endfor %}
              {% endif %}

              {% block main %}{% endblock %}
            </div>
          </div>

        </main>
      </div>

    </body>
    <footer class="pt-3 pb-1 text-muted text-center text-small bg-secondary">
      <p class="text-white">© 2021 Christian Schuzlendorff</p>
    </footer>

    </html>

myequis/templates/form-button-class.html
class="btn btn-primary pt-2 pb-2 pl-4 pr-4 m-1" 

myequis/templates/form-buttons-open.html
<div class="d-grid gap-2 d-md-flex justify-content-center">

myequis/templates/nav-back-item.html
  <li class="nav-item">
<!-- Navigate back to the previous URL. Be careful in use! -->
    <a class="btn btn-outline-primary mr-2 mt-1" href="{{request.META.HTTP_REFERER|escape}}">Back</a>
  </li>

myequis/templates/nav-close.html
</ul>

myequis/templates/nav-item.html
  <li class="nav-item">
    <a class="btn btn-outline-primary mr-2 mt-1" href={{ url }}>{{ title }}</a>
  </li>

myequis/templates/nav-line.html
<div class="d-flex flex-wrap  justify-content-end align-items-center  bg-primary border border-primary pl-3 pt-1 pb-1 pr-1">

  <div class='flex-grow-1 mr-2'>
    <p id='{{ title }}' class="h1 mb-0 mt-0 text-white" >
      {{ title }}
    </p>
  </div>

  <div class='btn-group' role='group'>

    {% if back_url is not None and back_url != 'None' %}
    <a href='#{{ back_url }}'>
      <button type="button" class="btn text-primary mr-1 btn-light">
        &#129145;
      </button>
    </a>
    {% endif %}

    {% if prev_url is not None and prev_url != 'None' %}
    <a href='#{{ prev_url }}'>
      <button type="button" class="btn text-primary mr-1 pr-2 pl-2 btn-light {{ prev_status }}">
        &#9650;
      </button>
    </a>
    {% endif %}

    <a href='#{{ next_url }}'>
      <button type="button" class="btn text-primary mr-1 pr-2 pl-2 btn-light {{ next_status }}">
        &#9660;
      </button>
    </a>

  </div>
</div>

myequis/templates/nav-open.html
<ul class="nav justify-content-end mb-2">

myequis/templates/page-title.html
<div class="lead bg-secondary border-bottom text-white text-center">
    {{ title }}
</div>

myequis/templates/section-nav-line.html
<div class="d-flex flex-wrap  justify-content-end align-items-center  bg-secondary border border-secondary pl-2 pt-2 pb-2 pr-2">

  <div class='flex-grow-1'>
    <p id='{{ title }}' class="h3 mb-0 mt-0 text-white" >
      {{ title }}
    </p>
  </div>

  <div>
    <div class="btn-group" role=:group">

      {% if back_url is not None %}
      <a href='#{{ back_url }}'>
        <button type="button" class="btn text-secondary mr-1 btn-light">
        &#129145;
        </button>
      </a>
      {% endif %}

      {% if prev_url is not None %}
      <a href='#{{ prev_url }}'>
        <button type="button" class="btn text-secondary mr-1 pr-2 pl-2 btn-light {{ prev_status }}">
          &#9650;
        </button>
      </a>
      {% endif %}

      <a href='#{{ next_url }}'>
        <button type="button" class="btn text-secondary mr-1 pr-2 pl-2 btn-light {{ next_status }}">
          &#9660;
        </button>
      </a>

    </div>
  </div>
</div>

myequis/templates/section-title.html
<h3 class="bg-secondary text-white pl-2 pt-2 pb-2">
  {{ title }}
</h3>

myequis/templates/subsection-title.html
<div class="border-bottom border-secondary w100 mb-2">
  <h3 class="pl-2 pt-4 mb-0">
    {{ title }}
  </h3>
</div>